---

- name: Install required packages for HTTPS repositories
  apt: name={{ item.package }} state=present update_cache=yes cache_valid_time=3600
  become: yes
  with_items:
    - package: apt-transport-https
    - package: ca-certificates

- name: Install APT repository keys
  apt_key: id={{ item.id }} url={{ item.url }} state=present
  become: yes
  with_items:
    - { id: "72ECF46A56B4AD39C907BBB71646B01B86E50310", url: "https://dl.yarnpkg.com/debian/pubkey.gpg" }
    - { id: "9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280", url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key" }

- name: Install APT repositories
  apt_repository: repo={{ item.repo }} state=present
  become: yes
  with_items:
    - repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    - repo: "deb https://deb.nodesource.com/node_10.x {{ ubuntu_codename }} main"
